const http = require('http');

const server = http.createServer((req, res) => {
  res.writeHead(200, { 'Content-Type': 'text/html' });
  res.end(`
    <!DOCTYPE html>
    <html>
      <head>
        <title>Legal Connect - Expo App</title>
        <style>
          body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', sans-serif;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
            background: linear-gradient(135deg, #1e1e2e 0%, #2d2d44 100%);
            color: white;
          }
          .container {
            text-align: center;
            padding: 40px;
          }
          h1 {
            margin: 0 0 20px 0;
            font-size: 2.5em;
          }
          .status {
            font-size: 1.2em;
            opacity: 0.8;
            margin: 20px 0;
          }
          .info {
            background: rgba(255, 255, 255, 0.1);
            padding: 20px;
            border-radius: 10px;
            margin-top: 30px;
            font-size: 0.9em;
          }
        </style>
      </head>
      <body>
        <div class="container">
          <h1>📱 Legal Connect</h1>
          <p class="status">✅ Expo App Server is Running</p>
          <div class="info">
            <p>Server is accessible via Expo Go</p>
            <p>App is ready for development</p>
          </div>
        </div>
      </body>
    </html>
  `);
});

const PORT = 8081;
server.listen(PORT, '0.0.0.0', () => {
  console.log(`
📱 Expo App Server
==================
✅ Server running on port ${PORT}
📍 Access via: http://0.0.0.0:${PORT}
🔍 Scan the QR code generated by generate-qr.js
  `);
});
