import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertTriangle, CalendarDays, CheckCircle2, Clock3, Play, RefreshCw, UserPlus } from "lucide-react";
import { Link } from "wouter";
import { useAuth } from "@/lib/auth";
import { greetingFor, workspaceRequest } from "@/lib/workspace";

type Member = { id: string; name: string; role: string };
type HearingOrder = { id: string; status: string; fileName: string; uploadedAt: string };
type Hearing = {
  matterId: string; title: string; caseNumber?: string | null; court?: string | null; room?: string | null;
  itemNumber?: string | null; time?: string | null; purpose?: string | null; assignedTo?: { id: string; name: string } | null;
  status: string; outcome?: string | null; nextDate?: string | null; nextPurpose?: string | null; orderStatus?: string | null;
  order?: HearingOrder | null; requiresSenior: boolean; clash: boolean;
};
type TodayData = {
  date: string; hasChamber: boolean; canAssign?: boolean; chamber?: { name: string };
  summary: { hearings: number; completed?: number; missingUpdates?: number; requiresSenior: number; unassigned: number; clashes: number };
  hearings: Hearing[]; attention: Array<{ type: string; matterId: string; title: string }>; eligibleMembers: Member[];
};

const PURPOSES = ["arguments", "cross_examination", "examination_in_chief", "evidence", "final_arguments", "reply", "rejoinder", "compliance", "filing", "orders", "miscellaneous", "other"];
const OUTCOMES = ["heard", "adjourned", "pass_over", "part_heard", "order_reserved", "notice_issued", "disposed", "not_reached", "other"];
const label = (value: string) => value.replace(/_/g, " ").toUpperCase();
const readableDate = (value: string) => new Intl.DateTimeFormat("en-IN", { weekday: "long", day: "numeric", month: "long" }).format(new Date(`${value}T12:00:00`));

export function AdvocateToday() {
  const { session } = useAuth();
  const client = useQueryClient();
  const [board, setBoard] = useState(false);
  const [closing, setClosing] = useState<Hearing | null>(null);
  const [picked, setPicked] = useState<Record<string, string>>({});
  const query = useQuery({ queryKey: ["advocate-today", session?.user.id], queryFn: () => workspaceRequest<TodayData>("/api/chamber/today", session?.token), enabled: Boolean(session?.token), staleTime: 15_000 });
  const refresh = () => client.invalidateQueries({ queryKey: ["advocate-today", session?.user.id] });
  const assign = useMutation({ mutationFn: ({ hearing, assignee }: { hearing: Hearing; assignee: string }) => workspaceRequest(`/api/chamber/today/hearings/${hearing.matterId}/assign`, session?.token, { method: "POST", body: JSON.stringify({ hearingDate: query.data?.date, hearingTime: hearing.time, assignedTo: assignee }) }), onSuccess: refresh });
  const accept = useMutation({ mutationFn: (hearing: Hearing) => workspaceRequest(`/api/chamber/today/hearings/${hearing.matterId}/accept`, session?.token, { method: "POST", body: JSON.stringify({ hearingDate: query.data?.date }) }), onSuccess: refresh });
  const hearings = useMemo(() => [...(query.data?.hearings || [])].sort((a, b) => Number(b.status === "unassigned") - Number(a.status === "unassigned") || Number(b.clash) - Number(a.clash) || String(a.time || "99:99").localeCompare(String(b.time || "99:99"))), [query.data]);

  if (query.isLoading) return <div className="lc-workspace-loading"><span className="lc-spinner" /><p>Opening today’s court board…</p></div>;
  if (query.isError) return <section className="lc-workspace-error"><AlertTriangle /><div><h2>Today is unavailable</h2><p>{query.error.message}</p></div><button className="lc-button lc-button-primary" onClick={() => query.refetch()}><RefreshCw /> Retry</button></section>;
  const data = query.data!;
  if (!data.hasChamber) return <section className="lc-workspace-page"><section className="lc-command-hero"><div><span className="lc-kicker">TODAY</span><h2>{greetingFor()}, {session?.user.name || "Counsel"}.</h2><p>No Chamber Command is configured for this account yet.</p><Link className="lc-button lc-button-primary" href="/advocate/chamber">Open Chamber settings</Link></div></section></section>;
  return <div className="lc-workspace-page">
    {closing && <HearingUpdateForm hearing={closing} date={data.date} token={session?.token} done={() => { setClosing(null); refresh(); }} />}
    <section className="lc-command-hero lc-advocate-command"><div><span className="lc-kicker">TODAY · {readableDate(data.date)}</span><h2>{greetingFor()}, {session?.user.name || "Counsel"}.</h2><p>{data.chamber?.name || "Your chamber"} · court-day status at a glance.</p><button className="lc-button lc-button-primary" onClick={() => setBoard(true)}><Play /> Start my court day</button></div><CalendarDays /></section>
    <section className="lc-workspace-metrics"><div><CalendarDays /><span><strong>{data.summary.hearings}</strong><small>Hearings</small></span></div><div><CheckCircle2 /><span><strong>{data.summary.completed || 0}</strong><small>Completed</small></span></div><div><AlertTriangle /><span><strong>{data.summary.missingUpdates || 0}</strong><small>Update required</small></span></div></section>
    {board && <section className="lc-operational-panel" style={{ marginBottom: 20 }}><header><div><span>Court day board</span><h2>Priority order</h2></div><button className="lc-button" onClick={() => setBoard(false)}>Close</button></header><div className="lc-chamber-task-list">{hearings.map((hearing) => <div key={hearing.matterId}><span><strong>{hearing.title}</strong><small>{hearing.status}</small></span><em>{hearing.time || "Time not recorded"}</em></div>)}</div></section>}
    <section className="lc-operational-panel"><header><div><span>Today’s matters</span><h2>Cause list</h2></div><Link href="/advocate/diary">Open diary</Link></header>{hearings.length ? <div className="lc-chamber-task-list">{hearings.map((hearing) => <HearingRow key={hearing.matterId} hearing={hearing} data={data} picked={picked[hearing.matterId] || ""} onPick={(value) => setPicked((state) => ({ ...state, [hearing.matterId]: value }))} onAssign={() => assign.mutate({ hearing, assignee: picked[hearing.matterId] })} onAccept={() => accept.mutate(hearing)} onClose={() => setClosing(hearing)} onRefresh={refresh} token={session?.token} date={data.date} currentUser={String(session?.user.id || "")} busy={assign.isPending || accept.isPending} />)}</div> : <div style={{ padding: 20 }}><p className="lc-inline-empty">No court matters scheduled for today.</p></div>}</section>
  </div>;
}

function HearingRow({ hearing, data, picked, onPick, onAssign, onAccept, onClose, onRefresh, token, date, currentUser, busy }: { hearing: Hearing; data: TodayData; picked: string; onPick: (id: string) => void; onAssign: () => void; onAccept: () => void; onClose: () => void; onRefresh: () => void; token?: string; date: string; currentUser: string; busy: boolean }) {
  const mine = hearing.assignedTo?.id === currentUser;
  const detail = [hearing.caseNumber, hearing.court, hearing.room ? `Room ${hearing.room}` : null, hearing.itemNumber ? `Item ${hearing.itemNumber}` : null, hearing.purpose].filter(Boolean).join(" · ") || "Court details not recorded";
  return <div><span><strong>{hearing.time ? `${hearing.time} · ` : ""}{hearing.title}</strong><small>{detail}</small>{hearing.assignedTo && <small>Assigned to {hearing.assignedTo.name}</small>}{hearing.outcome && <small>{label(hearing.outcome)}{hearing.nextDate ? ` · NDOH ${hearing.nextDate}` : ""}{hearing.nextPurpose ? ` · ${label(hearing.nextPurpose)}` : ""}</small>}{hearing.outcome && <CourtOrderPanel hearing={hearing} hearingDate={date} token={token} canUpload={Boolean(mine || data.canAssign)} canVerify={Boolean(data.canAssign)} onRefresh={onRefresh} />}</span><div className="lc-hero-button-row">{hearing.clash && <em style={{ color: "#b44747" }}>COURT CLASH</em>}<em>{label(hearing.status)}</em>{data.canAssign && hearing.status === "unassigned" && <><select aria-label={`Assign ${hearing.title}`} value={picked} onChange={(event) => onPick(event.target.value)}><option value="">Assign counsel…</option>{data.eligibleMembers.map((member) => <option key={member.id} value={member.id}>{member.name} · {member.role}</option>)}</select><button className="lc-sync-button" disabled={!picked || busy} onClick={onAssign}><UserPlus /> Assign</button></>}{mine && hearing.status === "assigned" && <button className="lc-sync-button" disabled={busy} onClick={onAccept}><CheckCircle2 /> Accept</button>}{(mine || data.canAssign) && !hearing.outcome && ["assigned", "accepted", "in_court"].includes(hearing.status) && <button className="lc-sync-button" onClick={onClose}><Clock3 /> Update hearing</button>}</div></div>;
}

function CourtOrderPanel({ hearing, hearingDate, token, canUpload, canVerify, onRefresh }: { hearing: Hearing; hearingDate: string; token?: string; canUpload: boolean; canVerify: boolean; onRefresh: () => void }) {
  const [progress, setProgress] = useState(0); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [correcting, setCorrecting] = useState(false); const [nextDate, setNextDate] = useState(hearing.nextDate || ""); const [nextPurpose, setNextPurpose] = useState(hearing.nextPurpose || "");
  const upload = async (file: File) => { setBusy(true); setError(""); try { const ticket = await workspaceRequest<{ orderId: string; uploadUrl: string; contentType: string }>(`/api/chamber/today/hearings/${hearing.matterId}/order-upload-url`, token, { method: "POST", body: JSON.stringify({ hearingDate, fileName: file.name, mimeType: file.type, sizeBytes: file.size, orderDate: hearingDate }) }); await new Promise<void>((resolve, reject) => { const request = new XMLHttpRequest(); request.open("PUT", ticket.uploadUrl); request.setRequestHeader("Content-Type", ticket.contentType); request.upload.onprogress = (event) => event.lengthComputable && setProgress(Math.round(event.loaded * 100 / event.total)); request.onload = () => request.status >= 200 && request.status < 300 ? resolve() : reject(new Error("S3 rejected the court-order upload.")); request.onerror = () => reject(new Error("Court-order upload was interrupted.")); request.send(file); }); await workspaceRequest(`/api/chamber/orders/${ticket.orderId}/complete`, token, { method: "POST", body: "{}" }); onRefresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Court-order upload failed."); } finally { setBusy(false); } };
  const view = async () => { try { const result = await workspaceRequest<{ viewUrl: string }>(`/api/chamber/orders/${hearing.order?.id}/view-url`, token); window.open(result.viewUrl, "_blank", "noopener,noreferrer"); } catch (cause) { setError(cause instanceof Error ? cause.message : "Court order could not be opened."); } };
  const verify = async (action: "matches" | "correct") => { setBusy(true); setError(""); try { await workspaceRequest(`/api/chamber/orders/${hearing.order?.id}/verify`, token, { method: "POST", body: JSON.stringify({ action, ...(action === "correct" ? { nextHearingDate: nextDate || null, nextPurpose: nextPurpose || null } : {}) }) }); onRefresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Verification failed."); } finally { setBusy(false); } };
  if (!hearing.order) return hearing.orderStatus === "not_expected" ? <small>COURT ORDER · NOT EXPECTED</small> : <span style={{ display: "block", marginTop: 8 }}>{canUpload && <label className="lc-sync-button">{busy ? `Uploading ${progress}%` : "Upload Court Order"}<input type="file" accept="application/pdf,image/jpeg,image/png" hidden disabled={busy} onChange={(event) => event.target.files?.[0] && upload(event.target.files[0])} /></label>}{error && <small style={{ color: "#b44747" }}>{error}</small>}</span>;
  return <span style={{ display: "block", marginTop: 8 }}><small>COURT ORDER · {label(hearing.order.status)}</small><button className="lc-sync-button" onClick={view}>View order</button>{canVerify && hearing.order.status === "verification_pending" && (correcting ? <span><input type="date" value={nextDate} onChange={(event) => setNextDate(event.target.value)} /><select value={nextPurpose} onChange={(event) => setNextPurpose(event.target.value)}><option value="">No purpose</option>{PURPOSES.map((purpose) => <option value={purpose} key={purpose}>{label(purpose)}</option>)}</select><button className="lc-sync-button" disabled={busy} onClick={() => verify("correct")}>Confirm correction</button></span> : <span><button className="lc-sync-button" disabled={busy} onClick={() => verify("matches")}>Everything matches</button><button className="lc-sync-button" onClick={() => setCorrecting(true)}>Correct hearing record</button></span>)}{error && <small style={{ color: "#b44747" }}>{error}</small>}</span>;
}

function HearingUpdateForm({ hearing, date, token, done }: { hearing: Hearing; date: string; token?: string; done: () => void }) {
  const [outcome, setOutcome] = useState("adjourned"); const [nextDate, setNextDate] = useState(""); const [nextPurpose, setNextPurpose] = useState(""); const [directions, setDirections] = useState(""); const [note, setNote] = useState(""); const [orderStatus, setOrderStatus] = useState("not_available"); const [dayConcluded, setDayConcluded] = useState(false); const [actionRequired, setActionRequired] = useState(false); const [actionTitle, setActionTitle] = useState(""); const [review, setReview] = useState(false); const [error, setError] = useState("");
  const save = useMutation({ mutationFn: () => workspaceRequest(`/api/chamber/today/hearings/${hearing.matterId}/close`, token, { method: "POST", body: JSON.stringify({ hearingDate: date, outcome, nextHearingDate: nextDate || null, nextPurpose: nextPurpose || null, courtDirections: directions || null, internalNote: note || null, orderStatus, dayConcluded, actionRequired, actionTitle: actionTitle || null }) }), onSuccess: done, onError: (cause: Error) => setError(cause.message) });
  return <section className="lc-operational-panel" style={{ marginBottom: 20 }}><header><div><span>Manual hearing closure</span><h2>{hearing.title}</h2></div><button className="lc-button" onClick={done}>Dismiss</button></header>{error && <p className="lc-error-banner">{error}</p>}{review ? <div><p>Confirm this manual record. It will keep any earlier hearing update in the matter history.</p><p><strong>{label(outcome)}</strong>{nextDate ? ` · Next hearing: ${nextDate}` : ""}{nextPurpose ? ` · ${label(nextPurpose)}` : ""}</p><div className="lc-hero-button-row"><button className="lc-button" onClick={() => setReview(false)}>Edit</button><button className="lc-button lc-button-primary" disabled={save.isPending} onClick={() => save.mutate()}>Confirm hearing update</button></div></div> : <div className="lc-form-grid"><label>Outcome<select value={outcome} onChange={(event) => setOutcome(event.target.value)}>{OUTCOMES.map((value) => <option key={value} value={value}>{label(value)}</option>)}</select></label>{outcome === "pass_over" && <label><input type="checkbox" checked={dayConcluded} onChange={(event) => setDayConcluded(event.target.checked)} /> Day concluded</label>}<label>Next hearing date<input type="date" disabled={outcome === "disposed" || (outcome === "pass_over" && !dayConcluded)} value={nextDate} onChange={(event) => setNextDate(event.target.value)} /></label><label>Next purpose<select value={nextPurpose} onChange={(event) => setNextPurpose(event.target.value)}><option value="">Not recorded</option>{PURPOSES.map((value) => <option key={value} value={value}>{label(value)}</option>)}</select></label><label>Order status<select value={orderStatus} onChange={(event) => setOrderStatus(event.target.value)}><option value="not_available">Not available</option><option value="not_expected">Not expected</option></select></label><label>Court directions<textarea value={directions} onChange={(event) => setDirections(event.target.value)} /></label><label>Internal chamber note<textarea value={note} onChange={(event) => setNote(event.target.value)} /></label><label><input type="checkbox" checked={actionRequired} onChange={(event) => setActionRequired(event.target.checked)} /> Create linked chamber follow-up</label>{actionRequired && <label>Follow-up title<input value={actionTitle} onChange={(event) => setActionTitle(event.target.value)} required /></label>}<button className="lc-button lc-button-primary" disabled={actionRequired && !actionTitle.trim()} onClick={() => setReview(true)}>Review update</button></div>}</section>;
}
