import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertTriangle, CalendarDays, CheckCircle2, Clock3, Play, RefreshCw, UserPlus, UsersRound } from "lucide-react";
import { Link } from "wouter";
import { useAuth } from "@/lib/auth";
import { greetingFor, workspaceRequest } from "@/lib/workspace";

type Member = { id: string; name: string; role: string };
type Hearing = { matterId: string; title: string; caseNumber?: string | null; court?: string | null; room?: string | null; itemNumber?: string | null; time?: string | null; purpose?: string | null; assignedTo?: { id: string; name: string } | null; status: string; outcome?: string | null; nextDate?: string | null; nextPurpose?: string | null; requiresSenior: boolean; clash: boolean };
type TodayData = { date: string; hasChamber: boolean; canAssign?: boolean; chamber?: { name: string }; summary: { hearings: number; completed?: number; missingUpdates?: number; requiresSenior: number; unassigned: number; clashes: number }; hearings: Hearing[]; attention: Array<{ type: string; matterId: string; title: string }>; eligibleMembers: Member[] };
const label = (v: string) => v.replace(/_/g, " ").toUpperCase();
const readableDate = (v: string) => new Intl.DateTimeFormat("en-IN", { weekday: "long", day: "numeric", month: "long" }).format(new Date(`${v}T12:00:00`));

export function AdvocateToday() {
  const { session } = useAuth(); const client = useQueryClient(); const [board, setBoard] = useState(false); const [closing, setClosing] = useState<Hearing | null>(null); const [picked, setPicked] = useState<Record<string, string>>({});
  const query = useQuery({ queryKey: ["advocate-today", session?.user.id], queryFn: () => workspaceRequest<TodayData>("/api/chamber/today", session?.token), enabled: Boolean(session?.token), staleTime: 15_000 });
  const refresh = () => client.invalidateQueries({ queryKey: ["advocate-today", session?.user.id] });
  const assign = useMutation({ mutationFn: ({ hearing, assignee }: { hearing: Hearing; assignee: string }) => workspaceRequest(`/api/chamber/today/hearings/${hearing.matterId}/assign`, session?.token, { method: "POST", body: JSON.stringify({ hearingDate: query.data?.date, hearingTime: hearing.time, assignedTo: assignee }) }), onSuccess: refresh });
  const accept = useMutation({ mutationFn: (hearing: Hearing) => workspaceRequest(`/api/chamber/today/hearings/${hearing.matterId}/accept`, session?.token, { method: "POST", body: JSON.stringify({ hearingDate: query.data?.date }) }), onSuccess: refresh });
  const hearings = useMemo(() => [...(query.data?.hearings || [])].sort((a, b) => Number(b.status === "unassigned") - Number(a.status === "unassigned") || Number(b.clash) - Number(a.clash) || String(a.time || "99:99").localeCompare(String(b.time || "99:99"))), [query.data]);
  if (query.isLoading) return <div className="lc-workspace-loading"><span className="lc-spinner" /><p>Opening today’s court board…</p></div>;
  if (query.isError) return <section className="lc-workspace-error"><AlertTriangle /><div><h2>Today is unavailable</h2><p>{query.error.message}</p></div><button className="lc-button lc-button-primary" onClick={() => query.refetch()}><RefreshCw /> Retry</button></section>;
  const data = query.data!;
  if (!data.hasChamber) return <section className="lc-workspace-page"><section className="lc-command-hero"><div><span className="lc-kicker">TODAY</span><h2>{greetingFor()}, {session?.user.name || "Counsel"}.</h2><p>No Chamber Command is configured for this account yet.</p><Link className="lc-button lc-button-primary" href="/advocate/chamber">Open Chamber settings</Link></div></section></section>;
  return <div className="lc-workspace-page">{closing && <HearingUpdateForm hearing={closing} date={data.date} token={session?.token} done={() => { setClosing(null); refresh(); }}/>}<section className="lc-command-hero lc-advocate-command"><div><span className="lc-kicker">TODAY · {readableDate(data.date)}</span><h2>{greetingFor()}, {session?.user.name || "Counsel"}.</h2><p>{data.chamber?.name || "Your chamber"} · court-day status at a glance.</p><button className="lc-button lc-button-primary" onClick={() => setBoard(true)}><Play /> Start my court day</button></div><CalendarDays /></section><section className="lc-workspace-metrics"><div><CalendarDays /><span><strong>{data.summary.hearings}</strong><small>Hearings</small></span></div><div><CheckCircle2 /><span><strong>{data.summary.completed || 0}</strong><small>Completed</small></span></div><div><AlertTriangle /><span><strong>{data.summary.missingUpdates || 0}</strong><small>Update required</small></span></div></section>{board && <section className="lc-operational-panel" style={{ marginBottom: 20 }}><header><div><span>Court day board</span><h2>Priority order</h2></div><button className="lc-button" onClick={() => setBoard(false)}>Close</button></header><div className="lc-chamber-task-list">{hearings.map(h => <div key={h.matterId}><span><strong>{h.title}</strong><small>{h.status}</small></span><em>{h.time || "Time not recorded"}</em></div>)}</div></section>}<section className="lc-operational-panel"><header><div><span>Today’s matters</span><h2>Cause list</h2></div><Link href="/advocate/diary">Open diary</Link></header>{hearings.length ? <div className="lc-chamber-task-list">{hearings.map(h => <HearingRow key={h.matterId} hearing={h} data={data} picked={picked[h.matterId] || ""} onPick={v => setPicked(s => ({ ...s, [h.matterId]: v }))} onAssign={() => assign.mutate({ hearing: h, assignee: picked[h.matterId] })} onAccept={() => accept.mutate(h)} onClose={() => setClosing(h)} currentUser={String(session?.user.id || "")} busy={assign.isPending || accept.isPending}/>)}</div> : <div style={{ padding: 20 }}><p className="lc-inline-empty">No court matters scheduled for today.</p></div>}</section></div>;
}

function HearingRow({ hearing, data, picked, onPick, onAssign, onAccept, onClose, currentUser, busy }: { hearing: Hearing; data: TodayData; picked: string; onPick: (id: string) => void; onAssign: () => void; onAccept: () => void; onClose: () => void; currentUser: string; busy: boolean }) {
  const mine = hearing.assignedTo?.id === currentUser;
  const detail = [hearing.caseNumber, hearing.court, hearing.room ? `Room ${hearing.room}` : null, hearing.itemNumber ? `Item ${hearing.itemNumber}` : null, hearing.purpose].filter(Boolean).join(" · ") || "Court details not recorded";
  return <div><span><strong>{hearing.time ? `${hearing.time} · ` : ""}{hearing.title}</strong><small>{detail}</small>{hearing.assignedTo && <small>Assigned to {hearing.assignedTo.name}</small>}{hearing.outcome && <small>{label(hearing.outcome)}{hearing.nextDate ? ` · NDOH ${hearing.nextDate}` : ""}{hearing.nextPurpose ? ` · ${label(hearing.nextPurpose)}` : ""}</small>}</span><div className="lc-hero-button-row">{hearing.clash && <em style={{ color: "#b44747" }}>COURT CLASH</em>}<em>{label(hearing.status)}</em>{data.canAssign && hearing.status === "unassigned" && <><select aria-label={`Assign ${hearing.title}`} value={picked} onChange={e => onPick(e.target.value)}><option value="">Assign counsel…</option>{data.eligibleMembers.map(m => <option key={m.id} value={m.id}>{m.name} · {m.role}</option>)}</select><button className="lc-sync-button" disabled={!picked || busy} onClick={onAssign}><UserPlus /> Assign</button></>}{mine && hearing.status === "assigned" && <button className="lc-sync-button" disabled={busy} onClick={onAccept}><CheckCircle2 /> Accept</button>}{(mine || data.canAssign) && !hearing.outcome && ["assigned", "accepted", "in_court"].includes(hearing.status) && <button className="lc-sync-button" onClick={onClose}><Clock3 /> Update hearing</button>}</div></div>;
}

function HearingUpdateForm({ hearing, date, token, done }: { hearing: Hearing; date: string; token?: string; done: () => void }) {
  const [outcome, setOutcome] = useState("adjourned"); const [nextDate, setNextDate] = useState(""); const [nextPurpose, setNextPurpose] = useState(""); const [directions, setDirections] = useState(""); const [note, setNote] = useState(""); const [orderStatus, setOrderStatus] = useState("not_available"); const [dayConcluded, setDayConcluded] = useState(false); const [actionRequired, setActionRequired] = useState(false); const [actionTitle, setActionTitle] = useState(""); const [review, setReview] = useState(false); const [error, setError] = useState("");
  const save = useMutation({ mutationFn: () => workspaceRequest(`/api/chamber/today/hearings/${hearing.matterId}/close`, token, { method: "POST", body: JSON.stringify({ hearingDate: date, outcome, nextHearingDate: nextDate || null, nextPurpose: nextPurpose || null, courtDirections: directions || null, internalNote: note || null, orderStatus, dayConcluded, actionRequired, actionTitle: actionTitle || null }) }), onSuccess: done, onError: (e: Error) => setError(e.message) });
  return <section className="lc-operational-panel" style={{ marginBottom: 20 }}><header><div><span>Manual hearing closure</span><h2>{hearing.title}</h2></div><button className="lc-button" onClick={done}>Dismiss</button></header>{error && <p className="lc-error-banner">{error}</p>}{review ? <div><p>Confirm this manual record. It will keep any earlier hearing update in the matter history.</p><p><strong>{label(outcome)}</strong>{nextDate ? ` · Next hearing: ${nextDate}` : ""}{nextPurpose ? ` · ${label(nextPurpose)}` : ""}</p><div className="lc-hero-button-row"><button className="lc-button" onClick={() => setReview(false)}>Edit</button><button className="lc-button lc-button-primary" disabled={save.isPending} onClick={() => save.mutate()}>Confirm hearing update</button></div></div> : <div className="lc-form-grid"><label>Outcome<select value={outcome} onChange={e => setOutcome(e.target.value)}>{["heard", "adjourned", "pass_over", "part_heard", "order_reserved", "notice_issued", "disposed", "not_reached", "other"].map(v => <option key={v} value={v}>{label(v)}</option>)}</select></label>{outcome === "pass_over" && <label><input type="checkbox" checked={dayConcluded} onChange={e => setDayConcluded(e.target.checked)} /> Day concluded</label>}<label>Next hearing date<input type="date" disabled={outcome === "disposed" || (outcome === "pass_over" && !dayConcluded)} value={nextDate} onChange={e => setNextDate(e.target.value)} /></label><label>Next purpose<select value={nextPurpose} onChange={e => setNextPurpose(e.target.value)}><option value="">Not recorded</option>{["arguments", "cross_examination", "examination_in_chief", "evidence", "final_arguments", "reply", "rejoinder", "compliance", "filing", "orders", "miscellaneous", "other"].map(v => <option key={v} value={v}>{label(v)}</option>)}</select></label><label>Order status<select value={orderStatus} onChange={e => setOrderStatus(e.target.value)}><option value="uploaded">Uploaded</option><option value="not_available">Not available</option><option value="not_expected">Not expected</option></select></label><label>Court directions<textarea value={directions} onChange={e => setDirections(e.target.value)} /></label><label>Internal chamber note<textarea value={note} onChange={e => setNote(e.target.value)} /></label><label><input type="checkbox" checked={actionRequired} onChange={e => setActionRequired(e.target.checked)} /> Create linked chamber follow-up</label>{actionRequired && <label>Follow-up title<input value={actionTitle} onChange={e => setActionTitle(e.target.value)} required /></label>}<button className="lc-button lc-button-primary" disabled={actionRequired && !actionTitle.trim()} onClick={() => setReview(true)}>Review update</button></div>}</section>;
}
